[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
# Deixamos o comando de start para o Dockerfile CMD
healthcheckPath = "/api/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[service]
internalPort = 3000
